In [2]:
import pandas as pd

In [3]:
# Selection of data

movies_df = pd.read_csv('imdb_data.csv', index_col='Title')
movies_df.head(5)

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [5]:
# Column as a series

col_series = movies_df['Genre']
print(type(col_series))
col_series.head(5)

<class 'pandas.core.series.Series'>

Title
Guardians of the Galaxy     Action,Adventure,Sci-Fi
Prometheus                 Adventure,Mystery,Sci-Fi
Split                               Horror,Thriller
Sing                        Animation,Comedy,Family
Suicide Squad              Action,Adventure,Fantasy
Name: Genre, dtype: object

In [10]:
# Column as a dataframe

col_df = movies_df[['Genre', 'Rating', 'Year']]  # we are passing the columns as a list to get a Dataframe output
print(type(col_df))
col_df.head(5)

<class 'pandas.core.frame.DataFrame'>

                                            Genre  Rating  Year
Title
Guardians of the Galaxy   Action,Adventure,Sci-Fi     8.1  2014
Prometheus               Adventure,Mystery,Sci-Fi     7.0  2012
Split                             Horror,Thriller     7.3  2016
Sing                      Animation,Comedy,Family     7.2  2016
Suicide Squad            Action,Adventure,Fantasy     6.2  2016

In [13]:
# Slicing of data - row wise (loc, iloc, ix) - [start:stop:step]
 
movies_df.loc['Guardians of the Galaxy']   # Explicit index based

Rank                                                                  1
Genre                                           Action,Adventure,Sci-Fi
Description           A group of intergalactic criminals are forced ...
Director                                                     James Gunn
Actors                Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
Year                                                               2014
Runtime (Minutes)                                                   121
Rating                                                             8.10
Votes                                                            757074
Revenue (Millions)                                               333.13
Metascore                                                         76.00
Name: Guardians of the Galaxy, dtype: object

In [14]:
movies_df.iloc[0]  # Implicit index based - Numerical index

Rank                                                                  1
Genre                                           Action,Adventure,Sci-Fi
Description           A group of intergalactic criminals are forced ...
Director                                                     James Gunn
Actors                Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
Year                                                               2014
Runtime (Minutes)                                                   121
Rating                                                             8.10
Votes                                                            757074
Revenue (Millions)                                               333.13
Metascore                                                         76.00
Name: Guardians of the Galaxy, dtype: object

In [15]:
# Slicing with Multiple Rows

movies_df.loc['Guardians of the Galaxy' : 'Sing']

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0

In [16]:
movies_df.iloc[0:4]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0

In [20]:
# Slicing both rows and columns

movies_df.loc[:'Sing', :'Director']

,Rank,Genre,Description,Director
Title,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet

In [18]:
movies_df.iloc[:4, :4]

,Rank,Genre,Description,Director
Title,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet

In [22]:
# Using ix - hybrid slicing

movies_df.ix[:4, :'Director'] # ix is deprecated since pandas 0.20.0

AttributeError: 'DataFrame' object has no attribute 'ix'

In [4]:
# Conditional data selection and filtering - because we never know what indexes we want to work on! (implicit/explicit)

movies_df[movies_df['Year'] == 2016] # Movies released in 2016

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
The Great Wall,6,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
La La Land,7,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
...,...,...,...,...,...,...,...,...,...,...,...
My Big Fat Greek Wedding 2,976,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
Amateur Night,978,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
It's Only the End of the World,979,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
Miracles from Heaven,981,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [5]:
movies_df[movies_df['Rating'] > 8.0] # movies with rating greater than 8.0

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
La La Land,7,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
Hacksaw Ridge,17,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
Lion,19,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0
Bahubali: The Beginning,27,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN
Interstellar,37,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
Star Wars: Episode VII - The Force Awakens,51,"Action,Adventure,Fantasy",Three decades after the defeat of the Galactic...,J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac, Domhna...",2015,136,8.1,661608,936.63,81.0
The Dark Knight,55,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
The Prestige,65,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0
Mad Max: Fury Road,68,"Action,Adventure,Sci-Fi",A woman rebels against a tyrannical ruler in p...,George Miller,"Tom Hardy, Charlize Theron, Nicholas Hoult, Zo...",2015,120,8.1,632842,153.63,90.0
Zootopia,75,"Animation,Adventure,Comedy","In a city of anthropomorphic animals, a rookie...",Byron Howard,"Ginnifer Goodwin, Jason Bateman, Idris Elba, J...",2016,108,8.1,296853,341.26,78.0
The Avengers,77,"Action,Sci-Fi",Earth's mightiest heroes must come together an...,Joss Whedon,"Robert Downey Jr., Chris Evans, Scarlett Johan...",2012,143,8.1,1045588,623.28,69.0
Inglourious Basterds,78,"Adventure,Drama,War","In Nazi-occupied France during World War II, a...",Quentin Tarantino,"Brad Pitt, Diane Kruger, Eli Roth,Mélanie Laurent",2009,153,8.3,959065,120.52,69.0
Inception,81,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
The Wolf of Wall Street,83,"Biography,Comedy,Crime","Based on the true story of Jordan Belfort, fro...",Martin Scorsese,"Leonardo DiCaprio, Jonah Hill, Margot Robbie,M...",2013,180,8.2,865134,116.87,75.0
Gone Girl,84,"Crime,Drama,Mystery",With his wife's disappearance having become th...,David Fincher,"Ben Affleck, Rosamund Pike, Neil Patrick Harri...",2014,149,8.1,636243,167.74,79.0
Prisoners,91,"Crime,Drama,Mystery",When Keller Dover's daughter and her friend go...,Denis Villeneuve,"Hugh Jackman, Jake Gyllenhaal, Viola Davis,Mel...",2013,153,8.1,431185,60.96,74.0
The Help,93,Drama,An aspiring author during the civil rights mov...,Tate Taylor,"Emma Stone, Viola Davis, Octavia Spencer, Bryc...",2011,146,8.1,342429,169.71,62.0
Kimi no na wa,97,"Animation,Drama,Fantasy",Two strangers find themselves linked in a biza...,Makoto Shinkai,"Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Nari...",2016,106,8.6,34110,4.68,79.0
The Departed,100,"Crime,Drama,Thriller",An undercover cop and a mole in the police att...,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...",2006,151,8.5,937414,132.37,85.0
12 Years a Slave,112,"Biography,Drama,History","In the antebellum United States, Solomon North...",Steve McQueen,"Chiwetel Ejiofor, Michael Kenneth Williams, Mi...",2013,134,8.1,486338,56.67,96.0
Harry Potter and the Deathly Hallows: Part 2,115,"Adventure,Drama,Fantasy","Harry, Ron and Hermione search for Voldemort's...",David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, M...",2011,130,8.1,590595,380.96,87.0
Dangal,118,"Action,Biography,Drama",Former wrestler Mahavir Singh Phogat and his t...,Nitesh Tiwari,"Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...",2016,161,8.8,48969,11.15,NaN
The Dark Knight Rises,125,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0
Whiplash,134,"Drama,Music",A promising young drummer enrolls at a cut-thr...,Damien Chazelle,"Miles Teller, J.K. Simmons, Melissa Benoist, P...",2014,107,8.5,477276,13.09,88.0
No Country for Old Men,137,"Crime,Drama,Thriller",Violence and mayhem ensue after a hunter stumb...,Ethan Coen,"Tommy Lee Jones, Javier Bardem, Josh Brolin, W...",2007,122,8.1,660286,74.27,91.0
Shutter Island,139,"Mystery,Thriller","In 1954, a U.S. marshal investigates the disap...",Martin Scorsese,"Leonardo DiCaprio, Emily Mortimer, Mark Ruffal...",2010,138,8.1,855604,127.97,63.0
Room,144,Drama,A young boy is raised within the confines of a...,Lenny Abrahamson,"Brie Larson, Jacob Tremblay, Sean Bridgers,Wen...",2015,118,8.2,224132,14.68,86.0
Django Unchained,145,"Drama,Western","With the help of a German bounty hunter , a fr...",Quentin Tarantino,"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio...",2012,165,8.4,1039115,162.80,81.0
Ah-ga-ssi,146,"Drama,Mystery,Romance",A woman is hired as a handmaiden to a Japanese...,Chan-wook Park,"Min-hee Kim, Jung-woo Ha, Jin-woong Jo, So-ri ...",2016,144,8.1,33418,2.01,84.0
Twin Peaks: The Missing Pieces,155,"Drama,Horror,Mystery",Twin Peaks before Twin Peaks (1990) and at the...,David Lynch,"Chris Isaak, Kiefer Sutherland, C.H. Evans, Sa...",2014,91,8.1,1973,NaN,NaN
Spotlight,193,"Crime,Drama,History",The true story of how the Boston Globe uncover...,Tom McCarthy,"Mark Ruffalo, Michael Keaton, Rachel McAdams, ...",2015,128,8.1,268282,44.99,93.0
Warrior,195,"Action,Drama,Sport",The youngest son of an alcoholic former boxer ...,Gavin O'Connor,"Tom Hardy, Nick Nolte, Joel Edgerton, Jennifer...",2011,140,8.2,355722,13.65,71.0
Into the Wild,198,"Adventure,Biography,Drama","After graduating from Emory University, top st...",Sean Penn,"Emile Hirsch, Vince Vaughn, Catherine Keener, ...",2007,148,8.1,459304,18.35,73.0
The Imitation Game,199,"Biography,Drama,Thriller","During World War II, mathematician Alan Turing...",Morten Tyldum,"Benedict Cumberbatch, Keira Knightley, Matthew...",2014,114,8.1,532353,91.12,73.0
Pan's Labyrinth,231,"Drama,Fantasy,War","In the falangist Spain of 1944, the bookish yo...",Guillermo del Toro,"Ivana Baquero, Ariadna Gil, Sergi López,Maribe...",2006,118,8.2,498879,37.62,98.0
The Grand Budapest Hotel,239,"Adventure,Comedy,Drama","The adventures of Gustave H, a legendary conci...",Wes Anderson,"Ralph Fiennes, F. Murray Abraham, Mathieu Amal...",2014,99,8.1,530881,59.07,88.0
Inside Out,242,"Animation,Adventure,Comedy",After young Riley is uprooted from her Midwest...,Pete Docter,"Amy Poehler, Bill Hader, Lewis Black, Mindy Ka...",2015,95,8.2,416689,356.45,94.0
The Intouchables,250,"Biography,Comedy,Drama",After he becomes a quadriplegic from a paragli...,Olivier Nakache,"François Cluzet, Omar Sy, Anne Le Ny, Audrey F...",2011,112,8.6,557965,13.18,57.0
There Will Be Blood,300,"Drama,History","A story of family, religion, hatred, oil and m...",Paul Thomas Anderson,"Daniel Day-Lewis, Paul Dano, Ciarán Hinds,Mart...",2007,158,8.1,400682,40.22,92.0
Rush,335,"Action,Biography,Drama",The merciless 1970s rivalry between Formula On...,Ron Howard,"Daniel Brühl, Chris Hemsworth, Olivia Wilde,Al...",2013,123,8.1,339722,26.90,75.0
The Bourne Ultimatum,428,"Action,Mystery,Thriller",Jason Bourne dodges a ruthless CIA official an...,Paul Greengrass,"Matt Damon, Edgar Ramírez, Joan Allen, Julia S...",2007,115,8.1,525700,227.14,85.0
3 Idiots,431,"Comedy,Drama",Two friends are searching for their long lost ...,Rajkumar Hirani,"Aamir Khan, Madhavan, Mona Singh, Sharman Joshi",2009,170,8.4,238789,6.52,67.0
Jagten,456,Drama,"A teacher lives a lonely life, all the while s...",Thomas Vinterberg,"Mads Mikkelsen, Thomas Bo Larsen, Annika Wedde...",2012,115,8.3,192263,0.61,76.0
The Lives of Others,477,"Drama,Thriller","In 1984 East Berlin, an agent of the secret po...",Florian Henckel von Donnersmarck,"Ulrich Mühe, Martina Gedeck,Sebastian Koch, Ul...",2006,137,8.5,278103,11.28,89.0
Paint It Black,479,Drama,A young woman attempts to deal with the death ...,Amber Tamblyn,"Alia Shawkat, Nancy Kwan, Annabelle Attanasio,...",2016,96,8.3,61,NaN,71.0
Up,500,"Animation,Adventure,Comedy",Seventy-eight year old Carl Fredricksen travel...,Pete Docter,"Edward Asner, Jordan Nagai, John Ratzenberger,...",2009,96,8.3,722203,292.98,88.0
Mommy,609,Drama,"A widowed single mother, raising her violent s...",Xavier Dolan,"Anne Dorval, Antoine-Olivier Pilon, Suzanne Cl...",2014,139,8.1,33560,3.49,74.0
WALL·E,635,"Animation,Adventure,Family","In the distant future, a small waste-collectin...",Andrew Stanton,"Ben Burtt, Elissa Knight, Jeff Garlin, Fred Wi...",2008,98,8.4,776897,223.81,NaN
Relatos salvajes,642,"Comedy,Drama,Thriller",Six short stories that explore the extremities...,Damián Szifron,"Darío Grandinetti, María Marull, Mónica Villa,...",2014,122,8.1,110100,3.08,77.0
Gran Torino,646,Drama,Disgruntled Korean War veteran Walt Kowalski s...,Clint Eastwood,"Clint Eastwood, Bee Vang, Christopher Carley,A...",2008,116,8.2,595779,148.09,NaN
Toy Story 3,689,"Animation,Adventure,Comedy",The toys are mistakenly delivered to a day-car...,Lee Unkrich,"Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty",2010,103,8.3,586669,414.98,92.0
Hachi: A Dog's Tale,696,"Drama,Family",A college professor's bond with the abandoned ...,Lasse Hallström,"Richard Gere, Joan Allen, Cary-Hiroyuki Tagawa...",2009,93,8.1,177602,NaN,61.0
Incendies,714,"Drama,Mystery,War",Twins journey to the Middle East to discover t...,Denis Villeneuve,"Lubna Azabal, Mélissa Désormeaux-Poulin, Maxim...",2010,131,8.2,92863,6.86,80.0
El secreto de sus ojos,743,"Drama,Mystery,Romance",A retired legal counselor writes a novel hopin...,Juan José Campanella,"Ricardo Darín, Soledad Villamil, Pablo Rago,Ca...",2009,129,8.2,144524,20.17,80.0
PK,766,"Comedy,Drama,Romance",A stranger in the city asks questions no one h...,Rajkumar Hirani,"Aamir Khan, Anushka Sharma, Sanjay Dutt,Boman ...",2014,153,8.2,103279,10.57,51.0
How to Train Your Dragon,773,"Animation,Action,Adventure",A hapless young Viking who aspires to hunt dra...,Dean DeBlois,"Jay Baruchel, Gerard Butler,Christopher Mintz-...",2010,98,8.1,523893,217.39,74.0
Koe no katachi,862,"Animation,Drama,Romance","The story revolves around Nishimiya Shoko, a g...",Naoko Yamada,"Miyu Irino, Saori Hayami, Aoi Yuki, Kenshô Ono",2016,129,8.4,2421,NaN,80.0
Taare Zameen Par,992,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0

In [8]:
movies_df[(2016 >= movies_df['Year'] >= 2010)] 

# The following error is thrown because the first condition evaluates to True and True is compared >= 2010

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [11]:
movies_df[((2016 >= movies_df['Year']) & (movies_df['Year'] >= 2010)) 
          & (movies_df['Rating'] < 6.0) 
          & (movies_df['Revenue (Millions)'] > movies_df['Revenue (Millions)'].quantile(0.75))
         ]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Fifty Shades of Grey,64,"Drama,Romance,Thriller",Literature student Anastasia Steele's life cha...,Sam Taylor-Johnson,"Dakota Johnson, Jamie Dornan, Jennifer Ehle,El...",2015,125,4.1,244474,166.15,46.0
Ghostbusters,80,"Action,Comedy,Fantasy","Following a ghost invasion of Manhattan, paran...",Paul Feig,"Melissa McCarthy, Kristen Wiig, Kate McKinnon,...",2016,116,5.3,147717,128.34,60.0
Transformers: Age of Extinction,127,"Action,Adventure,Sci-Fi",Autobots must escape sight from a bounty hunte...,Michael Bay,"Mark Wahlberg, Nicola Peltz, Jack Reynor, Stan...",2014,165,5.7,255483,245.43,32.0
The Twilight Saga: Breaking Dawn - Part 2,367,"Adventure,Drama,Fantasy","After the birth of Renesmee, the Cullens gathe...",Bill Condon,"Kristen Stewart, Robert Pattinson, Taylor Laut...",2012,115,5.5,194329,292.30,52.0
Grown Ups 2,395,Comedy,After moving his family back to his hometown t...,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",2013,101,5.4,114482,133.67,19.0
Clash of the Titans,576,"Action,Adventure,Fantasy","Perseus demigod, son of Zeus, battles the mini...",Louis Leterrier,"Sam Worthington, Liam Neeson, Ralph Fiennes,Ja...",2010,106,5.8,238206,163.19,39.0
Kickboxer: Vengeance,581,Action,A kick boxer is out to avenge his brother.,John Stockwell,"Dave Bautista, Alain Moussi, Gina Carano, Jean...",2016,90,4.9,6809,131.56,37.0
Teenage Mutant Ninja Turtles,658,"Action,Adventure,Comedy","When a kingpin threatens New York City, a grou...",Jonathan Liebesman,"Megan Fox, Will Arnett, William Fichtner, Noel...",2014,101,5.9,178527,190.87,31.0
Green Lantern,674,"Action,Adventure,Sci-Fi",Reckless test pilot Hal Jordan is granted an a...,Martin Campbell,"Ryan Reynolds, Blake Lively, Peter Sarsgaard,M...",2011,114,5.6,231907,116.59,39.0
G.I. Joe: Retaliation,879,"Action,Adventure,Sci-Fi",The G.I. Joes are not only fighting their mort...,Jon M. Chu,"Dwayne Johnson, Channing Tatum, Adrianne Palic...",2013,110,5.8,152145,122.51,41.0
The Twilight Saga: Breaking Dawn - Part 1,926,"Adventure,Drama,Fantasy",The Quileutes close in on expecting parents Ed...,Bill Condon,"Kristen Stewart, Robert Pattinson, Taylor Laut...",2011,117,4.9,190244,281.28,45.0
The Twilight Saga: Eclipse,942,"Adventure,Drama,Fantasy",As a string of mysterious killings grips Seatt...,David Slade,"Kristen Stewart, Robert Pattinson, Taylor Laut...",2010,124,4.9,192740,300.52,58.0